module.exports = [
    "In My Feelings",
    "I Like It",
    "Girls Like You",
    "Nice For What",
    "Lucid Dreams",
    "Better Now",
    "No Tears Left To Cry",
    "Psycho",
    "God's Plan",
    "God Is A Woman",
    "Delicate",
    "Taste",
    "The Middle",
    "Sad!",
    "Yes Indeed",
    "Meant To Be",
    "Friends", 
    "Perfect", 
    "Nonstop", 
    "Love Lies",
    "Mine", 
    "In My Blood", 
    "I'm Upset", 
    "Tequila",
    "One Kiss", 
    "Back To You", 
    "Apes**t", 
    "I Like Me Better", 
    "Never Be The Same",
    "Get Along", 
    "Youngblood", 
    "Don't Matter To Me", 
    "Whatever It Takes", 
    "Look Alive", 
    "Simple",
    "Moonlight", 
    "Mercy", 
    "Big Bank", 
    "This Is America"  
]